id: I8F008930
default_language: bo
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-09 15:01:44.158074
last_modified: 2023-02-09 15:01:44.158177
source_metadata:
  title: 'MSV 1,02: Poṣadhavastu'
  language: bo
bases:
  F90F:
    base_file: F90F.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
